Pytorch course

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1


Intro to tensors

In [2]:
# scalar 

scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item

<function Tensor.item>

In [7]:
# Vector
vector = torch.tensor([7,7])
vector.ndim
vector.shape

torch.Size([2])

In [8]:
MATRIX = torch.tensor([[7,8],[9,10]])
print(MATRIX)


tensor([[ 7,  8],
        [ 9, 10]])


In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]])

In [23]:
TENSOR.shape

torch.Size([2, 4, 3])

In [24]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

### Random tensors

In [29]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7299, 0.0820, 0.2492, 0.9127],
        [0.1346, 0.7999, 0.5746, 0.0585],
        [0.1906, 0.4693, 0.4246, 0.2523]])

In [30]:
random_tensor.ndim

2

In [32]:
# create a random tensor with similar shape to an image tensor
rand_image_size_tensor = torch.rand(size=(224,224,3))
rand_image_size_tensor.shape, rand_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Binary tensors (with 0 and 1)

In [33]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [34]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
# tensor with all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [36]:
ones.dtype

torch.float32

### Creating range of tensora and tensors-like

In [47]:
one_to_ten = torch.arange(1,10,1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
#creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors datatypes


In [57]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, 
                               device='cpu', 
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [58]:
float_32_tensor.dtype

torch.float64

Float 32 is default

In [64]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) 
float_16_tensor.dtype

torch.float16

In [65]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [67]:
int32_tensor = torch.tensor([3,6,9],dtype=int)
int32_tensor

tensor([3, 6, 9])

In [68]:
int32_tensor*float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

### Getting information from tensors

Once you've created tensors (or someone else or a PyTorch module has created them for you), you might want to get some information from them.

We've seen these before but three of the most common attributes you'll want to find out about tensors are:

    shape - what shape is the tensor? (some operations require specific shape rules)
    dtype - what datatype are the elements within the tensor stored in?
    device - what device is the tensor stored on? (usually GPU or CPU)


In [70]:
print("Tensor: ", random_tensor)
print("Shape: ", random_tensor.shape)
print("dtype: ", random_tensor.dtype)
print("device: ", random_tensor.device)

Tensor:  tensor([[0.7299, 0.0820, 0.2492, 0.9127],
        [0.1346, 0.7999, 0.5746, 0.0585],
        [0.1906, 0.4693, 0.4246, 0.2523]])
Shape:  torch.Size([3, 4])
dtype:  torch.float32
device:  cpu


### Manipulating tensors

Tensor operation:
* Addition
* Subtraction
* Manipulation (element-wise)
* Division
* Matrix multiplication

In [71]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [72]:
tensor * 10

tensor([10, 20, 30])

In [73]:
tensor - 10

tensor([-9, -8, -7])

In [74]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [75]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication
2 ways
1. element-wise multiplocation
2. Matrix multiplication (dot product)


In [76]:
print(tensor, "*", tensor)
print(f"= {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
= tensor([1, 4, 9])


In [77]:
# Matrix multiplication

torch.matmul(tensor, tensor)

tensor(14)

### The main two rules for matrix multiplication to remember are:

1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work
2. The resulting matrix has the shape of the outer dimensions:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`


We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:
* `torch.transpose(input, dim0, dim1)` - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
* `tensor.T` - where tensor is the desired tensor to transpose.

In [3]:
first_tensor = torch.rand(3,2)
second_tensor = torch.rand(3,2)

In [7]:
second_tensor.T
second_tensor.T.shape

torch.Size([2, 3])

In [12]:
torch.matmul(first_tensor, second_tensor.T)

tensor([[0.1163, 0.1691, 0.0874],
        [0.0498, 0.0699, 0.0395],
        [0.1121, 0.1556, 0.0906]])

In [14]:
torch.mm(first_tensor.T, second_tensor)

tensor([[0.2265, 0.0283],
        [0.3791, 0.0502]])

## Min, max, mean, sum, etc

In [27]:
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [17]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [18]:
x.max()

tensor(90)

In [23]:
x = x.type(torch.float32)
torch.mean(x), x.mean()

(tensor(45.), tensor(45.))

In [24]:
x.sum()

tensor(450.)

### Positional min and max

In [29]:
x.argmin()

tensor(0)

In [26]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes and input tensor to defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as original tensor
* Stacking - combine multiple tensors on top of each other
* Squeeze - removes all `1` dimensions from a tensor
* Unseens - add `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [49]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
 # Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# Changing z changing x because they share the same memory
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [59]:
# Stack tensors
x_stacked = torch.stack([x,x,x,x])
x_stacked, x_stacked.ndim

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 2)

In [62]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [64]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x)
y.size()
torch.Size([2, 2, 2])
y = torch.squeeze(x, 0)
y.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x, 1)
y.size()
torch.Size([2, 2, 1, 2])
y = torch.squeeze(x, (1, 2, 3))
torch.Size([2, 2, 2])

torch.Size([2, 2, 2])

In [65]:
x_reshaped.shape

torch.Size([1, 9])

In [66]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [67]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
x_reshaped.squeeze().shape

torch.Size([9])

In [69]:
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [70]:
x_stacked.squeeze(), x_stacked.squeeze().shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [75]:
sq = x_reshaped.squeeze()
sq, sq.unsqueeze(dim=1), sq.unsqueeze(dim=1).shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [76]:
# permute
x = torch.randn(2, 3, 5)
print(x.size())
torch.permute(x, (2, 0, 1)).size()

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

In [79]:
x_original = torch.rand(size=(224,224,3))

view = torch.permute(x_original, (2,0,1))
view.shape

torch.Size([3, 224, 224])

In [81]:
x_original[:,:,1] = 10
x_original

tensor([[[ 0.2518, 10.0000,  0.0178],
         [ 0.2165, 10.0000,  0.6362],
         [ 0.5787, 10.0000,  0.5177],
         ...,
         [ 0.6079, 10.0000,  0.7914],
         [ 0.7251, 10.0000,  0.4124],
         [ 0.4563, 10.0000,  0.2886]],

        [[ 0.5775, 10.0000,  0.4251],
         [ 0.6785, 10.0000,  0.3471],
         [ 0.4671, 10.0000,  0.7841],
         ...,
         [ 0.6320, 10.0000,  0.5277],
         [ 0.2507, 10.0000,  0.4242],
         [ 0.1518, 10.0000,  0.1884]],

        [[ 0.0543, 10.0000,  0.5723],
         [ 0.9701, 10.0000,  0.1609],
         [ 0.2872, 10.0000,  0.0212],
         ...,
         [ 0.5249, 10.0000,  0.0179],
         [ 0.6140, 10.0000,  0.1234],
         [ 0.2875, 10.0000,  0.2190]],

        ...,

        [[ 0.7360, 10.0000,  0.7046],
         [ 0.8080, 10.0000,  0.1897],
         [ 0.8730, 10.0000,  0.7276],
         ...,
         [ 0.1584, 10.0000,  0.0407],
         [ 0.9746, 10.0000,  0.1815],
         [ 0.9288, 10.0000,  0.9383]],

        [[

In [83]:
view

tensor([[[ 0.2518,  0.2165,  0.5787,  ...,  0.6079,  0.7251,  0.4563],
         [ 0.5775,  0.6785,  0.4671,  ...,  0.6320,  0.2507,  0.1518],
         [ 0.0543,  0.9701,  0.2872,  ...,  0.5249,  0.6140,  0.2875],
         ...,
         [ 0.7360,  0.8080,  0.8730,  ...,  0.1584,  0.9746,  0.9288],
         [ 0.7624,  0.8618,  0.4949,  ...,  0.5303,  0.1554,  0.8730],
         [ 0.8307,  0.1138,  0.1123,  ...,  0.7162,  0.5426,  0.3189]],

        [[10.0000, 10.0000, 10.0000,  ..., 10.0000, 10.0000, 10.0000],
         [10.0000, 10.0000, 10.0000,  ..., 10.0000, 10.0000, 10.0000],
         [10.0000, 10.0000, 10.0000,  ..., 10.0000, 10.0000, 10.0000],
         ...,
         [10.0000, 10.0000, 10.0000,  ..., 10.0000, 10.0000, 10.0000],
         [10.0000, 10.0000, 10.0000,  ..., 10.0000, 10.0000, 10.0000],
         [10.0000, 10.0000, 10.0000,  ..., 10.0000, 10.0000, 10.0000]],

        [[ 0.0178,  0.6362,  0.5177,  ...,  0.7914,  0.4124,  0.2886],
         [ 0.4251,  0.3471,  0.7841,  ...,  0

### Indexing (selection data from tensors)

In [87]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [88]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [89]:
x[0,0]

tensor([1, 2, 3])

In [90]:
x[0,1,2]

tensor(6)

In [93]:
x[0,0,1]

tensor(2)

In [94]:
x[0,1]

tensor([4, 5, 6])

In [97]:
x[:,:,1]


tensor([[2, 5, 8]])

In [96]:
x[:,2,:]

tensor([[7, 8, 9]])

### RyTorch tensors and NumPy

* Data in NumPy array, wanted in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch -> Numpy -> `torch.Tensor.numpy()`

In [101]:
# Numpy -> tensor
import numpy as np
import torch

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [100]:
array.dtype

dtype('float64')

In [103]:
# change the value of array
array = array+1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [105]:
# tensor to np_tensor
tensor = torch.ones(7)
np_tensor = tensor.numpy()
tensor, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility
trying to take random out of random

In short:
`start with random numbers -> tensor operations -> try to make better (again and again and again)`

To reduce randomness in neural networks and pytorch comes with the concept of a **random seed**.


In [107]:
torch.rand(3,3)

tensor([[0.9131, 0.0752, 0.3202],
        [0.4150, 0.5293, 0.0935],
        [0.3157, 0.8483, 0.6098]])

In [108]:
rand_tensor_A = torch.rand(3,4)
rand_tensor_B = torch.rand(3,4)

print(rand_tensor_A)
print(rand_tensor_B)
print(rand_tensor_B == rand_tensor_A)

tensor([[0.0382, 0.4029, 0.8785, 0.1722],
        [0.6411, 0.3173, 0.2081, 0.0928],
        [0.7124, 0.6339, 0.2758, 0.7699]])
tensor([[0.7199, 0.7051, 0.1089, 0.2522],
        [0.8826, 0.1589, 0.5794, 0.8302],
        [0.4352, 0.5384, 0.6389, 0.4329]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [111]:
# rand but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
rand_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
rand_tensor_D = torch.rand(3,4)

print(rand_tensor_C)
print(rand_tensor_D)
print(rand_tensor_C == rand_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Random seed doc https://pytorch.org/docs/stable/notes/randomness.html


### Running tensors on GPUs (and making faster computations)

Deep learning algorithms require a lot of numerical operations.

And by default these operations are often done on a CPU (computer processing unit).

However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

    Note: When I reference "GPU" throughout this course, I'm referencing a Nvidia GPU with CUDA enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.



In [118]:
import torch
print(torch.__version__)
torch.cuda.is_available()

2.0.1


False

In [113]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


In [115]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [117]:
torch.cuda.device_count()

0